# Generated by Django 5.0.7 on 2024-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitem', 'price')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('menuitem', 'price')},
        ),
    ]
