# Generated by Django 5.0.7 on 2024-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0005_alter_menuitem_inventory_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(default=None),
        ),
    ]
